// Code generated by cmd/generate; DO NOT EDIT.

package cmd

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/alpacahq/cli/internal/api"
	"github.com/alpacahq/cli/internal/cmdutil"
	"github.com/spf13/cobra"
)

var accountCmd = &cobra.Command{
	Use:   "account",
	Short: "Manage your trading account",
	Long:  "View account details, portfolio history, activity log, and account configuration.",
}

var accountConfigCmd = &cobra.Command{
	Use:   "config",
	Short: "Manage account configuration",
}

var activityCmd = &cobra.Command{
	Use:   "activity",
	Short: "Account activities (fills, dividends, transfers, etc.)",
}

var assetCmd = &cobra.Command{
	Use:   "asset",
	Short: "Browse assets",
	Long:  "List and look up equities, options contracts, treasuries, and corporate bonds available for trading.",
}

var calendarCmd = &cobra.Command{
	Use:   "calendar",
	Short: "Market calendar",
	Long:  "List trading days with open/close times for US equity and international markets.",
}

var clockCmd = &cobra.Command{
	Use:   "clock",
	Short: "Market clock",
	Long:  "Check whether markets are currently open and when they next open or close.",
}

var corporateActionCmd = &cobra.Command{
	Use:   "corporate-action",
	Short: "Corporate actions announcements",
	Long:  "Query corporate action announcements such as splits, dividends, mergers, and spin-offs.",
}

var dataCmd = &cobra.Command{
	Use:   "data",
	Short: "Access market data",
	Long:  "Historical and real-time market data for stocks, crypto, options, forex, and fixed income. Includes bars, quotes, trades, snapshots, auctions, screeners, and news.",
}

var dataCryptoCmd = &cobra.Command{
	Use:   "crypto",
	Short: "Crypto market data",
	Long:  "Bars, quotes, trades, snapshots, and orderbooks for crypto pairs.",
}

var dataFixedIncomeCmd = &cobra.Command{
	Use:   "fixed-income",
	Short: "Fixed income market data",
	Long:  "Latest prices and quotes for fixed income securities identified by ISIN.",
}

var dataForexCmd = &cobra.Command{
	Use:   "forex",
	Short: "Foreign exchange rate data",
}

var dataMetaCmd = &cobra.Command{
	Use:   "meta",
	Short: "Stock exchange and condition reference data",
}

var dataOptionCmd = &cobra.Command{
	Use:   "option",
	Short: "Options market data",
	Long:  "Bars, trades, snapshots, chains, latest quotes, and exchange/condition reference data for options.",
}

var locateCmd = &cobra.Command{
	Use:   "locate",
	Short: "Manage locate requests",
	Long:  "Create, list, and inspect stock locate requests for short sales.",
}

var optionCmd = &cobra.Command{
	Use:   "option",
	Short: "Options trading",
	Long:  "List option contracts, look up by symbol, and exercise or decline exercise. For option market data, use 'data option'.",
}

var orderCmd = &cobra.Command{
	Use:   "order",
	Short: "Manage orders",
	Long:  "Submit, list, replace, and cancel orders. Supports market, limit, stop, stop-limit, and trailing-stop order types with bracket (take-profit/stop-loss) legs.",
}

var positionCmd = &cobra.Command{
	Use:   "position",
	Short: "Manage positions",
	Long:  "List, inspect, and close open positions. Supports partial closes by quantity or percentage.",
}

var screenerCmd = &cobra.Command{
	Use:   "screener",
	Short: "Stock and crypto screener and market movers",
	Long:  "Most active stocks and top market movers by volume, trade count, or price change.",
}

var walletCmd = &cobra.Command{
	Use:   "wallet",
	Short: "Crypto funding wallets and transfers",
	Long:  "View crypto funding wallets, create and track transfers, and manage whitelisted withdrawal addresses.",
}

var walletTransferCmd = &cobra.Command{
	Use:   "transfer",
	Short: "Manage crypto transfers",
}

var walletWhitelistCmd = &cobra.Command{
	Use:   "whitelist",
	Short: "Manage whitelisted crypto addresses",
}

var watchlistCmd = &cobra.Command{
	Use:   "watchlist",
	Short: "Manage watchlists",
	Long:  "Create, update, and delete watchlists. Add or remove symbols by watchlist ID or name.",
}

var addAssetToWatchlistCmd = fetchCmd("add", api.AddAssetToWatchlistOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.AddAssetToWatchlistRequest{
		Symbol: cmdutil.Str(cmd, "symbol"),
	}
	return tradingClient.AddAssetToWatchlist(cmdutil.Str(cmd, "watchlist-id"), body)
})

var addAssetToWatchlistByNameCmd = fetchCmd("add-by-name", api.AddAssetToWatchlistByNameOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.AddAssetToWatchlistRequest{
		Symbol: cmdutil.Str(cmd, "symbol"),
	}
	return tradingClient.AddAssetToWatchlistByName(queryFromFlags(cmd, api.AddAssetToWatchlistByNameOp), body)
})

var calendarMarketCmd = fetchCmd("market", api.CalendarOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.Calendar(cmdutil.Str(cmd, "market"), queryFromFlags(cmd, api.CalendarOp))
})

var clockMarketsCmd = fetchCmd("markets", api.ClockOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.Clock(queryFromFlags(cmd, api.ClockOp))
})

var corporateActionsCmd = fetchCmd("corporate-actions", api.CorporateActionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CorporateActions(queryFromFlags(cmd, api.CorporateActionsOp))
})

var createCryptoTransferForAccountCmd = fetchCmd("create", api.CreateCryptoTransferForAccountOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.CreateCryptoTransferRequest{
		Address: cmdutil.Str(cmd, "address"),
		Amount:  cmdutil.Str(cmd, "amount"),
		Asset:   cmdutil.Str(cmd, "asset"),
		Chain:   api.CryptoChain(cmdutil.Str(cmd, "chain")),
	}
	return tradingClient.CreateCryptoTransferForAccount(body)
})

var createLocatesCmd = fetchCmd("create", api.CreateLocatesOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.CreateLocateRequest{
		AllOrNone: cmdutil.Bool(cmd, "all-or-none"),
		Qty:       cmdutil.Int(cmd, "qty"),
		Symbol:    cmdutil.Str(cmd, "symbol"),
	}
	if cmdutil.Changed(cmd, "limit-price") {
		v := cmdutil.Str(cmd, "limit-price")
		body.LimitPrice = &v
	}
	return tradingClient.CreateLocates(headersFromFlags(cmd, api.CreateLocatesOp), body)
})

var createWhitelistedAddressCmd = fetchCmd("add", api.CreateWhitelistedAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.CreateWhitelistedAddressRequest{
		Address: cmdutil.Str(cmd, "address"),
		Asset:   cmdutil.Str(cmd, "asset"),
		Chain:   api.CryptoChain(cmdutil.Str(cmd, "chain")),
	}
	return tradingClient.CreateWhitelistedAddress(body)
})

var cryptoBarsCmd = fetchCmd("bars", api.CryptoBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoBars(cmdutil.Str(cmd, "loc"), queryFromFlags(cmd, api.CryptoBarsOp))
})

var cryptoLatestBarsCmd = fetchCmd("latest-bars", api.CryptoLatestBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoLatestBars(cmdutil.Str(cmd, "loc"), queryFromFlags(cmd, api.CryptoLatestBarsOp))
})

var cryptoLatestOrderbooksCmd = fetchCmd("crypto-orderbook", api.CryptoLatestOrderbooksOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoLatestOrderbooks(cmdutil.Str(cmd, "loc"), queryFromFlags(cmd, api.CryptoLatestOrderbooksOp))
})

var cryptoLatestQuotesCmd = fetchCmd("latest-quotes", api.CryptoLatestQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoLatestQuotes(cmdutil.Str(cmd, "loc"), queryFromFlags(cmd, api.CryptoLatestQuotesOp))
})

var cryptoLatestTradesCmd = fetchCmd("latest-trades", api.CryptoLatestTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoLatestTrades(cmdutil.Str(cmd, "loc"), queryFromFlags(cmd, api.CryptoLatestTradesOp))
})

var cryptoQuotesCmd = fetchCmd("quotes", api.CryptoQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoQuotes(cmdutil.Str(cmd, "loc"), queryFromFlags(cmd, api.CryptoQuotesOp))
})

var cryptoSnapshotsCmd = fetchCmd("snapshots", api.CryptoSnapshotsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoSnapshots(cmdutil.Str(cmd, "loc"), queryFromFlags(cmd, api.CryptoSnapshotsOp))
})

var cryptoTradesCmd = fetchCmd("trades", api.CryptoTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.CryptoTrades(cmdutil.Str(cmd, "loc"), queryFromFlags(cmd, api.CryptoTradesOp))
})

var deleteAllOpenPositionsCmd = fetchCmd("close-all", api.DeleteAllOpenPositionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.DeleteAllOpenPositions(queryFromFlags(cmd, api.DeleteAllOpenPositionsOp))
})

var deleteAllOrdersCmd = fetchCmd("cancel-all", api.DeleteAllOrdersOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.DeleteAllOrders()
})

var deleteOpenPositionCmd = fetchCmd("close", api.DeleteOpenPositionOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.DeleteOpenPosition(normalizePathParam(cmdutil.Str(cmd, "symbol-or-asset-id")), queryFromFlags(cmd, api.DeleteOpenPositionOp))
})

var deleteOrderByOrderIDCmd = fetchCmd("cancel", api.DeleteOrderByOrderIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteOrderByOrderID(cmdutil.Str(cmd, "order-id")))
})

var deleteWatchlistByIDCmd = fetchCmd("delete", api.DeleteWatchlistByIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteWatchlistByID(cmdutil.Str(cmd, "watchlist-id")))
})

var deleteWatchlistByNameCmd = fetchCmd("delete-by-name", api.DeleteWatchlistByNameOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteWatchlistByName(queryFromFlags(cmd, api.DeleteWatchlistByNameOp)))
})

var deleteWhitelistedAddressCmd = fetchCmd("delete", api.DeleteWhitelistedAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.DeleteWhitelistedAddress(cmdutil.Str(cmd, "whitelisted-address-id")))
})

var fixedIncomeLatestPricesCmd = fetchCmd("latest-prices", api.FixedIncomeLatestPricesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.FixedIncomeLatestPrices(queryFromFlags(cmd, api.FixedIncomeLatestPricesOp))
})

var fixedIncomeLatestQuotesCmd = fetchCmd("latest-quotes", api.FixedIncomeLatestQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.FixedIncomeLatestQuotes(queryFromFlags(cmd, api.FixedIncomeLatestQuotesOp))
})

var getAccountCmd = fetchCmd("get", api.GetAccountOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAccount()
})

var getAccountActivitiesCmd = fetchCmd("list", api.GetAccountActivitiesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetAccountActivities(queryFromFlags(cmd, api.GetAccountActivitiesOp)))
})

var getAccountActivitiesByActivityTypeCmd = fetchCmd("list-by-type", api.GetAccountActivitiesByActivityTypeOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.GetAccountActivitiesByActivityType(cmdutil.Str(cmd, "activity-type"), queryFromFlags(cmd, api.GetAccountActivitiesByActivityTypeOp)))
})

var getAccountConfigCmd = fetchCmd("get", api.GetAccountConfigOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAccountConfig()
})

var getAccountPortfolioHistoryCmd = fetchCmd("portfolio", api.GetAccountPortfolioHistoryOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAccountPortfolioHistory(queryFromFlags(cmd, api.GetAccountPortfolioHistoryOp))
})

var getAllOpenPositionsCmd = fetchCmd("list", api.GetAllOpenPositionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAllOpenPositions()
})

var getAllOrdersCmd = fetchCmd("list", api.GetAllOrdersOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetAllOrders(queryFromFlags(cmd, api.GetAllOrdersOp))
})

var getCryptoFundingTransferCmd = fetchCmd("get", api.GetCryptoFundingTransferOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetCryptoFundingTransfer(cmdutil.Str(cmd, "transfer-id"))
})

var getCryptoTransferEstimateCmd = fetchCmd("estimate", api.GetCryptoTransferEstimateOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetCryptoTransferEstimate(queryFromFlags(cmd, api.GetCryptoTransferEstimateOp))
})

var getLocateCmd = fetchCmd("get", api.GetLocateOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetLocate(cmdutil.Str(cmd, "locate-id"))
})

var getOpenPositionCmd = fetchCmd("get", api.GetOpenPositionOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOpenPosition(normalizePathParam(cmdutil.Str(cmd, "symbol-or-asset-id")))
})

var getOptionContractSymbolOrIDCmd = fetchCmd("get", api.GetOptionContractSymbolOrIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOptionContractSymbolOrID(cmdutil.Str(cmd, "symbol-or-id"))
})

var getOptionsContractsCmd = fetchCmd("contracts", api.GetOptionsContractsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOptionsContracts(queryFromFlags(cmd, api.GetOptionsContractsOp))
})

var getOrderByClientOrderIDCmd = fetchCmd("get-by-client-id", api.GetOrderByClientOrderIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOrderByClientOrderID(queryFromFlags(cmd, api.GetOrderByClientOrderIDOp))
})

var getOrderByOrderIDCmd = fetchCmd("get", api.GetOrderByOrderIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetOrderByOrderID(cmdutil.Str(cmd, "order-id"), queryFromFlags(cmd, api.GetOrderByOrderIDOp))
})

var getV2AssetsCmd = fetchCmd("list", api.GetV2AssetsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetV2Assets(queryFromFlags(cmd, api.GetV2AssetsOp))
})

var getV2AssetsSymbolOrAssetIDCmd = fetchCmd("get", api.GetV2AssetsSymbolOrAssetIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetV2AssetsSymbolOrAssetID(cmdutil.Str(cmd, "symbol-or-asset-id"))
})

var getV2CorporateActionsAnnouncementsCmd = fetchCmd("list", api.GetV2CorporateActionsAnnouncementsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetV2CorporateActionsAnnouncements(queryFromFlags(cmd, api.GetV2CorporateActionsAnnouncementsOp))
})

var getV2CorporateActionsAnnouncementsIDCmd = fetchCmd("get", api.GetV2CorporateActionsAnnouncementsIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetV2CorporateActionsAnnouncementsID(cmdutil.Str(cmd, "id"))
})

var getWatchlistByIDCmd = fetchCmd("get", api.GetWatchlistByIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetWatchlistByID(cmdutil.Str(cmd, "watchlist-id"))
})

var getWatchlistByNameCmd = fetchCmd("get-by-name", api.GetWatchlistByNameOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetWatchlistByName(queryFromFlags(cmd, api.GetWatchlistByNameOp))
})

var getWatchlistsCmd = fetchCmd("list", api.GetWatchlistsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.GetWatchlists()
})

var latestRatesCmd = fetchCmd("latest", api.LatestRatesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.LatestRates(queryFromFlags(cmd, api.LatestRatesOp))
})

var listCryptoFundingTransfersCmd = fetchCmd("list", api.ListCryptoFundingTransfersOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListCryptoFundingTransfers()
})

var listCryptoFundingWalletsCmd = fetchCmd("list", api.ListCryptoFundingWalletsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListCryptoFundingWallets(queryFromFlags(cmd, api.ListCryptoFundingWalletsOp))
})

var listLocateQuotesCmd = fetchCmd("quotes", api.ListLocateQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListLocateQuotes(queryFromFlags(cmd, api.ListLocateQuotesOp))
})

var listLocatesCmd = fetchCmd("list", api.ListLocatesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListLocates(queryFromFlags(cmd, api.ListLocatesOp))
})

var listWhitelistedAddressCmd = fetchCmd("list", api.ListWhitelistedAddressOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.ListWhitelistedAddress()
})

var logosCmd = fetchCmd("logo", api.LogosOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.Logos(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.LogosOp)))
})

var mostActivesCmd = fetchCmd("most-actives", api.MostActivesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.MostActives(queryFromFlags(cmd, api.MostActivesOp))
})

var moversCmd = fetchCmd("movers", api.MoversOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.Movers(cmdutil.Str(cmd, "market-type"), queryFromFlags(cmd, api.MoversOp))
})

var newsCmd = fetchCmd("news", api.NewsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.News(queryFromFlags(cmd, api.NewsOp))
})

var optionBarsCmd = fetchCmd("bars", api.OptionBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionBars(queryFromFlags(cmd, api.OptionBarsOp))
})

var optionChainCmd = fetchCmd("chain", api.OptionChainOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionChain(cmdutil.Str(cmd, "underlying-symbol"), queryFromFlags(cmd, api.OptionChainOp))
})

var optionDoNotExerciseCmd = fetchCmd("do-not-exercise", api.OptionDoNotExerciseOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.OptionDoNotExercise(cmdutil.Str(cmd, "symbol-or-contract-id")))
})

var optionExerciseCmd = fetchCmd("exercise", api.OptionExerciseOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(tradingClient.OptionExercise(cmdutil.Str(cmd, "symbol-or-contract-id")))
})

var optionLatestQuotesCmd = fetchCmd("latest-quotes", api.OptionLatestQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionLatestQuotes(queryFromFlags(cmd, api.OptionLatestQuotesOp))
})

var optionLatestTradesCmd = fetchCmd("latest-trades", api.OptionLatestTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionLatestTrades(queryFromFlags(cmd, api.OptionLatestTradesOp))
})

var optionMetaConditionsCmd = fetchCmd("conditions", api.OptionMetaConditionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.OptionMetaConditions(cmdutil.Str(cmd, "ticktype")))
})

var optionMetaExchangesCmd = fetchCmd("exchanges", api.OptionMetaExchangesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.OptionMetaExchanges())
})

var optionSnapshotsCmd = fetchCmd("snapshot", api.OptionSnapshotsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionSnapshots(queryFromFlags(cmd, api.OptionSnapshotsOp))
})

var optionTradesCmd = fetchCmd("trades", api.OptionTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.OptionTrades(queryFromFlags(cmd, api.OptionTradesOp))
})

var patchAccountConfigCmd = fetchCmd("set", api.PatchAccountConfigOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.AccountConfigurations{}
	var changed bool
	if cmdutil.Changed(cmd, "disable-overnight-trading") {
		body.DisableOvernightTrading = cmdutil.Bool(cmd, "disable-overnight-trading")
		changed = true
	}
	if cmdutil.Changed(cmd, "fractional-trading") {
		body.FractionalTrading = cmdutil.Bool(cmd, "fractional-trading")
		changed = true
	}
	if cmdutil.Changed(cmd, "max-margin-multiplier") {
		body.MaxMarginMultiplier = cmdutil.Str(cmd, "max-margin-multiplier")
		changed = true
	}
	if cmdutil.Changed(cmd, "max-options-trading-level") {
		body.MaxOptionsTradingLevel = cmdutil.Int(cmd, "max-options-trading-level")
		changed = true
	}
	if cmdutil.Changed(cmd, "no-shorting") {
		body.NoShorting = cmdutil.Bool(cmd, "no-shorting")
		changed = true
	}
	if cmdutil.Changed(cmd, "ptp-no-exception-entry") {
		body.PtpNoExceptionEntry = cmdutil.Bool(cmd, "ptp-no-exception-entry")
		changed = true
	}
	if cmdutil.Changed(cmd, "suspend-trade") {
		body.SuspendTrade = cmdutil.Bool(cmd, "suspend-trade")
		changed = true
	}
	if cmdutil.Changed(cmd, "trade-confirm-email") {
		body.TradeConfirmEmail = cmdutil.Str(cmd, "trade-confirm-email")
		changed = true
	}
	if !changed {
		return nil, fmt.Errorf("specify at least one flag to change (see '%s --help')", cmd.CommandPath())
	}
	return tradingClient.PatchAccountConfig(body)
})

var patchOrderByOrderIDCmd = fetchCmd("replace", api.PatchOrderByOrderIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.PatchOrderRequest{}
	var changed bool
	if cmdutil.Changed(cmd, "advanced-instructions") {
		if err := json.Unmarshal([]byte(cmdutil.Str(cmd, "advanced-instructions")), &body.AdvancedInstructions); err != nil {
			return nil, fmt.Errorf("--advanced-instructions: %w", err)
		}
		changed = true
	}
	if cmdutil.Changed(cmd, "client-order-id") {
		body.ClientOrderID = cmdutil.Str(cmd, "client-order-id")
		changed = true
	}
	if cmdutil.Changed(cmd, "limit-price") {
		body.LimitPrice = cmdutil.Str(cmd, "limit-price")
		changed = true
	}
	if cmdutil.Changed(cmd, "notional") {
		body.Notional = cmdutil.Str(cmd, "notional")
		changed = true
	}
	if cmdutil.Changed(cmd, "qty") {
		body.Qty = cmdutil.Str(cmd, "qty")
		changed = true
	}
	if cmdutil.Changed(cmd, "stop-price") {
		body.StopPrice = cmdutil.Str(cmd, "stop-price")
		changed = true
	}
	if cmdutil.Changed(cmd, "time-in-force") {
		body.TimeInForce = api.TimeInForce(cmdutil.Str(cmd, "time-in-force"))
		changed = true
	}
	if cmdutil.Changed(cmd, "trail") {
		body.Trail = cmdutil.Str(cmd, "trail")
		changed = true
	}
	if !changed {
		return nil, fmt.Errorf("specify at least one flag to change (see '%s --help')", cmd.CommandPath())
	}
	return tradingClient.PatchOrderByOrderID(cmdutil.Str(cmd, "order-id"), body)
})

var postOrderCmd = fetchCmd("submit", api.PostOrderOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.CreateOrderRequest{
		ClientOrderID:  cmdutil.Str(cmd, "client-order-id"),
		ExtendedHours:  cmdutil.Bool(cmd, "extended-hours"),
		LimitPrice:     cmdutil.Str(cmd, "limit-price"),
		Notional:       cmdutil.Str(cmd, "notional"),
		OrderClass:     api.OrderClass(cmdutil.Str(cmd, "order-class")),
		PositionIntent: api.PositionIntent(cmdutil.Str(cmd, "position-intent")),
		Qty:            cmdutil.Str(cmd, "qty"),
		Side:           api.OrderSide(cmdutil.Str(cmd, "side")),
		StopPrice:      cmdutil.Str(cmd, "stop-price"),
		Symbol:         cmdutil.Str(cmd, "symbol"),
		TimeInForce:    api.TimeInForce(cmdutil.Str(cmd, "time-in-force")),
		TrailPercent:   cmdutil.Str(cmd, "trail-percent"),
		TrailPrice:     cmdutil.Str(cmd, "trail-price"),
		Type:           api.OrderType(cmdutil.Str(cmd, "type")),
	}
	if cmdutil.Changed(cmd, "advanced-instructions") {
		if err := json.Unmarshal([]byte(cmdutil.Str(cmd, "advanced-instructions")), &body.AdvancedInstructions); err != nil {
			return nil, fmt.Errorf("--advanced-instructions: %w", err)
		}
	}
	if cmdutil.Changed(cmd, "legs") {
		if err := json.Unmarshal([]byte(cmdutil.Str(cmd, "legs")), &body.Legs); err != nil {
			return nil, fmt.Errorf("--legs: %w", err)
		}
	}
	if hookResult, err := postOrderHook(cmd, body); err != nil {
		return nil, err
	} else if hookResult != nil {
		return hookResult, nil
	}
	return tradingClient.PostOrder(body)
}, configureOrderSubmit)

var postWatchlistCmd = fetchCmd("create", api.PostWatchlistOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.CreateWatchlistRequest{
		Name: cmdutil.Str(cmd, "name"),
	}
	if s := cmdutil.Str(cmd, "symbols"); s != "" {
		body.Symbols = strings.Split(s, ",")
	}
	return tradingClient.PostWatchlist(body)
})

var ratesCmd = fetchCmd("rates", api.RatesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.Rates(queryFromFlags(cmd, api.RatesOp))
})

var removeAssetFromWatchlistCmd = fetchCmd("remove", api.RemoveAssetFromWatchlistOp, func(cmd *cobra.Command, args []string) (any, error) {
	return tradingClient.RemoveAssetFromWatchlist(cmdutil.Str(cmd, "watchlist-id"), cmdutil.Str(cmd, "symbol"))
})

var stockAuctionSingleCmd = fetchCmd("auction", api.StockAuctionSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockAuctionSingle(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.StockAuctionSingleOp))
})

var stockAuctionsCmd = fetchCmd("auctions", api.StockAuctionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockAuctions(queryFromFlags(cmd, api.StockAuctionsOp))
})

var stockBarSingleCmd = fetchCmd("bars", api.StockBarSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockBarSingle(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.StockBarSingleOp))
})

var stockBarsCmd = fetchCmd("multi-bars", api.StockBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockBars(queryFromFlags(cmd, api.StockBarsOp))
})

var stockLatestBarSingleCmd = fetchCmd("latest-bar", api.StockLatestBarSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestBarSingle(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.StockLatestBarSingleOp))
})

var stockLatestBarsCmd = fetchCmd("latest-bars", api.StockLatestBarsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestBars(queryFromFlags(cmd, api.StockLatestBarsOp))
})

var stockLatestQuoteSingleCmd = fetchCmd("latest-quote", api.StockLatestQuoteSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestQuoteSingle(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.StockLatestQuoteSingleOp))
})

var stockLatestQuotesCmd = fetchCmd("latest-quotes", api.StockLatestQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestQuotes(queryFromFlags(cmd, api.StockLatestQuotesOp))
})

var stockLatestTradeSingleCmd = fetchCmd("latest-trade", api.StockLatestTradeSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestTradeSingle(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.StockLatestTradeSingleOp))
})

var stockLatestTradesCmd = fetchCmd("latest-trades", api.StockLatestTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockLatestTrades(queryFromFlags(cmd, api.StockLatestTradesOp))
})

var stockMetaConditionsCmd = fetchCmd("conditions", api.StockMetaConditionsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.StockMetaConditions(cmdutil.Str(cmd, "ticktype"), queryFromFlags(cmd, api.StockMetaConditionsOp)))
})

var stockMetaExchangesCmd = fetchCmd("exchanges", api.StockMetaExchangesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.StockMetaExchanges())
})

var stockQuoteSingleCmd = fetchCmd("quotes", api.StockQuoteSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockQuoteSingle(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.StockQuoteSingleOp))
})

var stockQuotesCmd = fetchCmd("multi-quotes", api.StockQuotesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockQuotes(queryFromFlags(cmd, api.StockQuotesOp))
})

var stockSnapshotSingleCmd = fetchCmd("snapshot", api.StockSnapshotSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.StockSnapshotSingle(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.StockSnapshotSingleOp)))
})

var stockSnapshotsCmd = fetchCmd("multi-snapshots", api.StockSnapshotsOp, func(cmd *cobra.Command, args []string) (any, error) {
	return voidResponse(dataClient.StockSnapshots(queryFromFlags(cmd, api.StockSnapshotsOp)))
})

var stockTradeSingleCmd = fetchCmd("trades", api.StockTradeSingleOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockTradeSingle(cmdutil.Str(cmd, "symbol"), queryFromFlags(cmd, api.StockTradeSingleOp))
})

var stockTradesCmd = fetchCmd("multi-trades", api.StockTradesOp, func(cmd *cobra.Command, args []string) (any, error) {
	return dataClient.StockTrades(queryFromFlags(cmd, api.StockTradesOp))
})

var updateWatchlistByIDCmd = fetchCmd("update", api.UpdateWatchlistByIDOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.UpdateWatchlistRequest{}
	var changed bool
	if cmdutil.Changed(cmd, "name") {
		body.Name = cmdutil.Str(cmd, "name")
		changed = true
	}
	if cmdutil.Changed(cmd, "symbols") {
		if s := cmdutil.Str(cmd, "symbols"); s != "" {
			body.Symbols = strings.Split(s, ",")
		}
		changed = true
	}
	if !changed {
		return nil, fmt.Errorf("specify at least one flag to change (see '%s --help')", cmd.CommandPath())
	}
	return tradingClient.UpdateWatchlistByID(cmdutil.Str(cmd, "watchlist-id"), body)
})

var updateWatchlistByNameCmd = fetchCmd("update-by-name", api.UpdateWatchlistByNameOp, func(cmd *cobra.Command, args []string) (any, error) {
	body := &api.UpdateWatchlistRequest{}
	var changed bool
	if cmdutil.Changed(cmd, "new-name") {
		body.Name = cmdutil.Str(cmd, "new-name")
		changed = true
	}
	if cmdutil.Changed(cmd, "symbols") {
		if s := cmdutil.Str(cmd, "symbols"); s != "" {
			body.Symbols = strings.Split(s, ",")
		}
		changed = true
	}
	if !changed {
		return nil, fmt.Errorf("specify at least one flag to change (see '%s --help')", cmd.CommandPath())
	}
	return tradingClient.UpdateWatchlistByName(queryFromFlags(cmd, api.UpdateWatchlistByNameOp), body)
}, func(c *cobra.Command) {
	c.Flags().String("new-name", "", "The new watchlist name.")
})

func init() {
	attachCmd(calendarCmd, api.LegacyCalendarOp, func(cmd *cobra.Command, args []string) (any, error) {
		return voidResponse(tradingClient.LegacyCalendar(queryFromFlags(cmd, api.LegacyCalendarOp)))
	})
	attachCmd(clockCmd, api.LegacyClockOp, func(cmd *cobra.Command, args []string) (any, error) {
		return tradingClient.LegacyClock()
	})

	accountCmd.AddCommand(accountConfigCmd)
	accountCmd.AddCommand(activityCmd)
	dataCmd.AddCommand(dataCryptoCmd)
	dataCmd.AddCommand(dataFixedIncomeCmd)
	dataCmd.AddCommand(dataForexCmd)
	dataCmd.AddCommand(dataMetaCmd)
	dataCmd.AddCommand(dataOptionCmd)
	dataCmd.AddCommand(screenerCmd)
	walletCmd.AddCommand(walletTransferCmd)
	walletCmd.AddCommand(walletWhitelistCmd)

	watchlistCmd.AddCommand(addAssetToWatchlistCmd)
	watchlistCmd.AddCommand(addAssetToWatchlistByNameCmd)
	calendarCmd.AddCommand(calendarMarketCmd)
	clockCmd.AddCommand(clockMarketsCmd)
	dataCmd.AddCommand(corporateActionsCmd)
	walletTransferCmd.AddCommand(createCryptoTransferForAccountCmd)
	locateCmd.AddCommand(createLocatesCmd)
	walletWhitelistCmd.AddCommand(createWhitelistedAddressCmd)
	dataCryptoCmd.AddCommand(cryptoBarsCmd)
	dataCryptoCmd.AddCommand(cryptoLatestBarsCmd)
	dataCmd.AddCommand(cryptoLatestOrderbooksCmd)
	dataCryptoCmd.AddCommand(cryptoLatestQuotesCmd)
	dataCryptoCmd.AddCommand(cryptoLatestTradesCmd)
	dataCryptoCmd.AddCommand(cryptoQuotesCmd)
	dataCryptoCmd.AddCommand(cryptoSnapshotsCmd)
	dataCryptoCmd.AddCommand(cryptoTradesCmd)
	positionCmd.AddCommand(deleteAllOpenPositionsCmd)
	orderCmd.AddCommand(deleteAllOrdersCmd)
	positionCmd.AddCommand(deleteOpenPositionCmd)
	orderCmd.AddCommand(deleteOrderByOrderIDCmd)
	watchlistCmd.AddCommand(deleteWatchlistByIDCmd)
	watchlistCmd.AddCommand(deleteWatchlistByNameCmd)
	walletWhitelistCmd.AddCommand(deleteWhitelistedAddressCmd)
	dataFixedIncomeCmd.AddCommand(fixedIncomeLatestPricesCmd)
	dataFixedIncomeCmd.AddCommand(fixedIncomeLatestQuotesCmd)
	accountCmd.AddCommand(getAccountCmd)
	activityCmd.AddCommand(getAccountActivitiesCmd)
	activityCmd.AddCommand(getAccountActivitiesByActivityTypeCmd)
	accountConfigCmd.AddCommand(getAccountConfigCmd)
	accountCmd.AddCommand(getAccountPortfolioHistoryCmd)
	positionCmd.AddCommand(getAllOpenPositionsCmd)
	orderCmd.AddCommand(getAllOrdersCmd)
	walletTransferCmd.AddCommand(getCryptoFundingTransferCmd)
	walletTransferCmd.AddCommand(getCryptoTransferEstimateCmd)
	locateCmd.AddCommand(getLocateCmd)
	positionCmd.AddCommand(getOpenPositionCmd)
	optionCmd.AddCommand(getOptionContractSymbolOrIDCmd)
	optionCmd.AddCommand(getOptionsContractsCmd)
	orderCmd.AddCommand(getOrderByClientOrderIDCmd)
	orderCmd.AddCommand(getOrderByOrderIDCmd)
	assetCmd.AddCommand(getV2AssetsCmd)
	assetCmd.AddCommand(getV2AssetsSymbolOrAssetIDCmd)
	corporateActionCmd.AddCommand(getV2CorporateActionsAnnouncementsCmd)
	corporateActionCmd.AddCommand(getV2CorporateActionsAnnouncementsIDCmd)
	watchlistCmd.AddCommand(getWatchlistByIDCmd)
	watchlistCmd.AddCommand(getWatchlistByNameCmd)
	watchlistCmd.AddCommand(getWatchlistsCmd)
	dataForexCmd.AddCommand(latestRatesCmd)
	walletTransferCmd.AddCommand(listCryptoFundingTransfersCmd)
	walletCmd.AddCommand(listCryptoFundingWalletsCmd)
	locateCmd.AddCommand(listLocateQuotesCmd)
	locateCmd.AddCommand(listLocatesCmd)
	walletWhitelistCmd.AddCommand(listWhitelistedAddressCmd)
	dataCmd.AddCommand(logosCmd)
	screenerCmd.AddCommand(mostActivesCmd)
	screenerCmd.AddCommand(moversCmd)
	dataCmd.AddCommand(newsCmd)
	dataOptionCmd.AddCommand(optionBarsCmd)
	dataOptionCmd.AddCommand(optionChainCmd)
	optionCmd.AddCommand(optionDoNotExerciseCmd)
	optionCmd.AddCommand(optionExerciseCmd)
	dataOptionCmd.AddCommand(optionLatestQuotesCmd)
	dataOptionCmd.AddCommand(optionLatestTradesCmd)
	dataOptionCmd.AddCommand(optionMetaConditionsCmd)
	dataOptionCmd.AddCommand(optionMetaExchangesCmd)
	dataOptionCmd.AddCommand(optionSnapshotsCmd)
	dataOptionCmd.AddCommand(optionTradesCmd)
	accountConfigCmd.AddCommand(patchAccountConfigCmd)
	orderCmd.AddCommand(patchOrderByOrderIDCmd)
	orderCmd.AddCommand(postOrderCmd)
	watchlistCmd.AddCommand(postWatchlistCmd)
	dataForexCmd.AddCommand(ratesCmd)
	watchlistCmd.AddCommand(removeAssetFromWatchlistCmd)
	dataCmd.AddCommand(stockAuctionSingleCmd)
	dataCmd.AddCommand(stockAuctionsCmd)
	dataCmd.AddCommand(stockBarSingleCmd)
	dataCmd.AddCommand(stockBarsCmd)
	dataCmd.AddCommand(stockLatestBarSingleCmd)
	dataCmd.AddCommand(stockLatestBarsCmd)
	dataCmd.AddCommand(stockLatestQuoteSingleCmd)
	dataCmd.AddCommand(stockLatestQuotesCmd)
	dataCmd.AddCommand(stockLatestTradeSingleCmd)
	dataCmd.AddCommand(stockLatestTradesCmd)
	dataMetaCmd.AddCommand(stockMetaConditionsCmd)
	dataMetaCmd.AddCommand(stockMetaExchangesCmd)
	dataCmd.AddCommand(stockQuoteSingleCmd)
	dataCmd.AddCommand(stockQuotesCmd)
	dataCmd.AddCommand(stockSnapshotSingleCmd)
	dataCmd.AddCommand(stockSnapshotsCmd)
	dataCmd.AddCommand(stockTradeSingleCmd)
	dataCmd.AddCommand(stockTradesCmd)
	watchlistCmd.AddCommand(updateWatchlistByIDCmd)
	watchlistCmd.AddCommand(updateWatchlistByNameCmd)
}
